name: Build params

on:
  pull_request:
    branches:
      main

jobs:  
  runs-on: ubuntu-latest

  minify: 
    steps:
    - uses: actions/checkout@v2

    - name: Auto Minify
      uses: nizarmah/auto-minify@v2.1
      with:
        output: build
        overwrite: true
        maxdepth: 1

    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
